name: Build Hydra32

on:
push:
branches:
- main
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: ESP-IDF Build
    uses: espressif/esp-idf-ci-action@v1

  - name: Build firmware
    run: |
      . $IDF_PATH/export.sh
      idf.py build

  - name: Upload firmware
    uses: actions/upload-artifact@v4
    with:
      name: hydra32-firmware
      path: |
        build/*.bin
        build/*.elf
        build/*.map
